name = "hola"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "hola_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "hola.wasm"
command = "npm run build:release"
